algo = input('Digite algo: ')
print('O tipo primitivo desse valor é:', type(algo))
print('Só tem espaço? : ', algo.isspace())
print('E um número?: ', algo.isnumeric())
print('E alfabético?: ', algo.isalpha())
print('E alfanumérico?: ', algo.isalnum())
print('Está em maiúsculo?: ', algo.isupper())
print('Esté em minusculo?: ', algo.islower())
print('Está capitalizada?: ', algo.istitle())